# Generated by Django 4.1.5 on 2023-01-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_advocate_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='company_id',
            new_name='company',
        ),
    ]
